classurvey/urls.py
from django.urls import path
from . import views

app_name = 'classurvey'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('instructions/', views.instructions_view, name='instructions'),
    path('taxonomy/', views.taxonomy_view, name='taxonomy'),
    path('user-data/', views.user_details_view, name='user_details'),
    path('annotate-sound/',views.annotate_sound_view, name='main'),
    path('batch-end/', views.batch_end_view, name='batch_end'),
    path('data-end/', views.data_end_view, name='data_end'),
    path('results/', views.results_view, name='results'),
    path('export/', views.export_view, name='export'),
]

fs_experiment/urls.py
from django.contrib import admin
from django.urls import path, include


def crash_me(request):
    raise Exception('I am a test exception')

urlpatterns = [
    path('', include('classurvey.urls')),
    path('admin/', admin.site.urls),
    path('crash_me/', crash_me),
]

classurvey/models.py
from django.db import models


# sounds for testing
class TestSound(models.Model):
    sound_id = models.CharField(max_length=50)
    sound_class = models.CharField(max_length=50)
    sound_group = models.IntegerField()
    
    def __str__(self):
        return f"<TestSound {self.sound_id}>"

class ClassChoice(models.Model):
    class_key = models.CharField(max_length=10)
    class_name = models.CharField(max_length=50)
    top_level = models.CharField(max_length=20)
    description = models.CharField(max_length=255, null=True)
    examples = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return f"<ClassChoice {self.class_name}>"

class TopLevel(models.Model):
    top_level_name = models.CharField(max_length=10)
    top_level_description = models.CharField(max_length=255)

    def __str__(self):
        return f"<TopLevel {self.class_name}>"
    
class SoundAnswer(models.Model):
    user_id = models.CharField(max_length=50)  # random generate
    test_sound = models.ForeignKey(TestSound, on_delete=models.CASCADE)
    date_created = models.DateTimeField('Creation date', auto_now_add=True) #timezone aware

    # NOTE: If you change the keys, you have to be careful
    # to change them manually in annotate_sound.html file.

    # Import choices and put them in a tuple.
    chosen_class = models.CharField(max_length=15, default="")
    likert_choices = ((1, 'Very Unconfident'), (2, 'Unconfident'), (3, 'Neutral'), (4, 'Confident'), (5, 'Very Confident'))
    confidence = models.IntegerField(choices=likert_choices,default="")
    comment = models.CharField(max_length=100, null=True, blank=True, default="")

class UserDetailsModel(models.Model):
    user_id = models.CharField(max_length=50) #, unique=True
    ip_address = models.GenericIPAddressField(null=True)
    user_name = models.CharField(max_length=50, null=True, default="")
    date_created = models.DateTimeField('Creation date', auto_now_add=True)

classurvey/forms.py
from django import forms
from .models import SoundAnswer, UserDetailsModel, ClassChoice


class SoundAnswerForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        test_choices = ClassChoice.objects.values_list('class_key', 'class_name')
        self.fields['chosen_class'].widget = forms.RadioSelect(choices=tuple(test_choices))

    class Meta:
        model = SoundAnswer
        fields = ('chosen_class', 'confidence','comment')
        labels = {
            'chosen_class': 'Which is the most suitable category for this sound?',
            'confidence': 'How confident are you about your answer?',
            'comment': 'Anything to add?'
        }
        widgets = {
            'confidence': forms.RadioSelect,
            'comment': forms.Textarea(attrs={'class': 'textarea-comment'}),
        }


class UserDetailsForm(forms.ModelForm):

    class Meta:
        model = UserDetailsModel
        fields = ('user_name',)
        labels = {
            'user_name': 'Username:'
        }
        widgets = {
            'user_name': forms.Textarea(attrs={'class': 'textarea-username'}),
        }

classurvey/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils import timezone

from collections import Counter

from .models import SoundAnswer, TestSound, ClassChoice, UserDetailsModel, TopLevel
from .forms import SoundAnswerForm, UserDetailsForm

import random


def user_id_from_request(request):
    ''' Generate random user id. '''
    user_id = request.session.get('user_id', None)
    if user_id is None:
        user_id = 'user_' + str(random.randint(10, 9999999))
        request.session['user_id'] = user_id
    return user_id

def make_sound_order(request):
    group_number = request.session['group_number']

    # retrieve sound ids for one group
    test_sound_ids_in_group = TestSound.objects.filter(sound_group=group_number).values_list('id', flat=True)

    sound_order = request.session.get('sound_order', None)
    if sound_order is None:
        sound_order = list(test_sound_ids_in_group)
        random.shuffle(sound_order)

        request.session['sound_order'] = sound_order
        # print(request.session['sound_order'])
    return sound_order

def get_ip_address(request):
    user_ip_address = request.META.get('HTTP_X_FORWARDED_FOR')
    if user_ip_address:
        raw_address = user_ip_address.split(',')[0]
    else:
        raw_address = request.META.get('REMOTE_ADDR')
    return '.'.join(raw_address.split('.')[:-1])

def groups_already_done_for_user(request,user_id):
    groups_already_done = SoundAnswer.objects.filter(user_id=user_id).values_list(
        'test_sound__sound_group', flat=True).distinct()
    groups_already_done = list(groups_already_done)
    return groups_already_done

def assign_group(request, user_id):
    ''' 
    Assign one group to the user and save it to the session.
    '''
    # How many groups exist.
    available_groups = TestSound.objects.values_list('sound_group', flat=True).distinct()
    # Groups assigned to anyone.
    all_assigned_groups = SoundAnswer.objects.values_list(
        'test_sound__sound_group', flat=True).distinct()
    # Groups already assigned to the user. If it is empty, none are done.
    # groups_already_done_user = SoundAnswer.objects.filter(user_id=user_id).values_list(
    #     'test_sound__sound_group', flat=True).distinct()
    print(f"Number of available groups: {len(available_groups)}")
    print(f"Annotated groups: {len(all_assigned_groups)}")

    # Retrieve group from session, if any
    selected_group = request.session.get('group_number', None)
    # Find the first unassigned group to anyone.
    remaining_groups = list(set(available_groups) - set(all_assigned_groups))
    # Assign a group
    if remaining_groups:
        # Select next group
        selected_group = remaining_groups[0]  # random.choice(remaining_groups)
        request.session['group_number'] = selected_group
        request.session['sound_order'] = None
        print(f"Selected group: {selected_group}")
        return selected_group
    else:
        # All groups have been assigned, redirect to a page that says they are no more for now.
        print(f"No more groups")
        return 'done'

def get_next_sound_for_user(request):
    '''
    Retrieve the sounds that belong to a group and each time return one random
    sound until no more sound are remaining. 
    '''
    user_id = user_id_from_request(request)
    group_number = request.session['group_number']
    ordered_sound_ids = make_sound_order(request)
    # unique answered sounds
    test_sound_ids_already_answered = SoundAnswer.objects.filter(
        test_sound_id__in=ordered_sound_ids, user_id=user_id, test_sound__sound_group=int(group_number)).values_list(
        'test_sound_id', flat=True).distinct()
    current_sound_index = len(ordered_sound_ids) - len(test_sound_ids_already_answered) 
    if 0 == current_sound_index:
        return None
    else:
        next_sound_id = ordered_sound_ids[current_sound_index-1]
        next_sound = TestSound.objects.get(id=next_sound_id)
        return next_sound

def sounds_sizes(request, group_number):
    '''
    Returns the total size of sounds for a user and how many are answered already.
    '''
    user_id = user_id_from_request(request)

    test_sound_ids_in_group = TestSound.objects.filter(
        sound_group=group_number).values_list('id', flat=True)
    test_sound_ids_already_answered = SoundAnswer.objects.filter(
        test_sound_id__in=test_sound_ids_in_group, user_id=user_id).values_list('test_sound_id', flat=True)

    total_sounds_size = len(test_sound_ids_in_group)
    answered_sounds_size = len(test_sound_ids_already_answered)
    return total_sounds_size, answered_sounds_size

def check_group_complete(request, group_number):
    ''' 
    Check if a user has annotated all sounds in a group.
    '''    
    all_sounds_size, answered_sounds_size = sounds_sizes(request, group_number)
    completed = False
    if all_sounds_size <= answered_sounds_size:
        completed = True
    return completed

def get_test_descriptions():
    ''' Get descriptions for each category. '''
    test_choices = ClassChoice.objects.values_list(
        'class_key', 'description', 'examples')
    return test_choices

def get_class_tooltip(class_description, class_example):
    if class_example:
        return f'{class_description} Examples: {class_example}'
    else:
        return f'{class_description}'

def home_view(request):
    user_id = user_id_from_request(request)
    already_assigned_groups = groups_already_done_for_user(request, user_id)

    if len(already_assigned_groups) != 0: # if 0 then just assign group
        prev_group = already_assigned_groups[-1]
        if check_group_complete(request, prev_group) == False: # if not finish
            # print("You didnt finish:(")
            if request.method == 'POST':
                action = request.POST.get('action')
                if action == 'continue':
                    # go to unfinished question
                    return redirect(reverse('classurvey:main'))
                elif action == 'restart': 
                    # discard popup and redirect to start experiment
                    group = assign_group(request, user_id)
                    if 'done' == group: return redirect(reverse('classurvey:data_end'))
                    return render(request, 'classurvey/home.html', {'show_popup': False})
            else: # if not finished and not press button
                return render(request, 'classurvey/home.html', {'show_popup': True})
        else: # if prev is complete
            group = assign_group(request, user_id)
            if 'done' == group: return redirect(reverse('classurvey:data_end'))
            return render(request, 'classurvey/home.html', {'show_popup': False})
    else: # if it first time
        group = assign_group(request, user_id)
        return render(request, 'classurvey/home.html', {'show_popup': False})

def data_end_view(request):
    if request.method == 'POST':
        if 'clear_session_cache' in request.POST:
            request.session.flush()
            return redirect('classurvey:home')
    return render(request, 'classurvey/data_end.html')

def instructions_view(request):
    return render(request, 'classurvey/instructions.html')

def taxonomy_view(request):
    top_levels = ClassChoice.objects.values_list('top_level',flat=True).distinct()
    level_group = {}
    top_level_description = {}
    for top_level in top_levels:
        rows = ClassChoice.objects.filter(top_level=top_level)
        level_group[top_level] = list(rows)    
        top_level_description[top_level] = TopLevel.objects.get(top_level_name=top_level).top_level_description
    return render(request, 'classurvey/taxonomy.html', {
        'level_group': level_group, 'top_level_description':top_level_description
    })

def user_details_view(request):
    '''
    Form with user data and ip address.
    '''
    ip_address = get_ip_address(request)

    if request.method == 'POST':
        form = UserDetailsForm(request.POST)
        if form.is_valid():
            request.session['user_details'] = form.cleaned_data
            request.session.save()

            response = form.save(commit=False)
            response.ip_address = ip_address
            response.user_id = request.session['user_id']
            response.save()
            return redirect(reverse('classurvey:main'))
    else:
        # store user details to prefill
        stored_user_details = request.session.get('user_details', None)
        form = UserDetailsForm(initial=stored_user_details)
    return render(request, 'classurvey/user_details.html', {'form': form})

# annotate one sound
def annotate_sound_view(request):

    user_id = user_id_from_request(request)
    group_number = request.session['group_number']

    all_sounds_size, answered_sounds_size = sounds_sizes(request, group_number)
    current_sound_number = answered_sounds_size + 1

    if request.POST:
        form = SoundAnswerForm(request.POST)

        test_sound = TestSound.objects.get(id=request.POST.get('test_sound_id'))

        if form.is_valid():
            existing_sound_answer = SoundAnswer.objects.filter(test_sound=test_sound, user_id=user_id)
            if existing_sound_answer:
                existing_sound_answer = existing_sound_answer[0]
                # print(existing_sound_answer)
                existing_sound_answer.date_created = timezone.now()
                existing_sound_answer.chosen_class = form.cleaned_data['chosen_class']
                existing_sound_answer.confidence = form.cleaned_data['confidence']
                existing_sound_answer.comment = form.cleaned_data['comment']
                existing_sound_answer.save()
            else: 
                sound_answer = form.save(commit=False)

classurvey/templates/classurvey/annotate_sound.html
{% extends 'classurvey/base.html' %}
{% load dict_key %}

{% block content %}


<div class="container-main">
    <div class="card card-question">
        <div class="card-header">
            <h2>Sound annotation [{{ answered_sounds_size }} / {{ all_sounds_size }}]</h2>
        </div>
        <div class="card-body">
            
            <form method="post" novalidate autocomplete="off">
                {% csrf_token %}
                <input type="hidden" name="test_sound_id" value="{{ test_sound.id }}">
                <fieldset>
                    <div class="row">
                        <div class="col-12 d-none d-md-block">
                            <div class="center">
                                <div class="encoder_iframe_wrapper">
                                    <iframe id="encoder_iframe" frameborder="0" scrolling="no" width="481" height="86"></iframe>
                                </div>
                            </div>
                        </div>
                        <div class="col-12 d-md-none">
                            <div class="center">
                                <div class="encoder_iframe_wrapper">
                                    <iframe id="encoder_iframe_small" frameborder="0" scrolling="no" width="375" height="30"></iframe>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="class-label">
                            {{ form.chosen_class.label }}
                        </div>
                        <div class="error-class">
                            {{ form.chosen_class.errors }}
                        </div>
                        {% for option in form.chosen_class %}
                        {% if option.data.value == "m-sp" %}
                        <div class="col-12 col-lg-4 offset-lg-2">
                            <div class="topclass-names">
                                MUSIC
                            </div>
                            {% elif option.data.value == "is-p" %}
                            <div class="topclass-names">
                                INSTRUMENT SAMPLES
                            </div>
                            {% elif option.data.value == "sp-s" %}
                            <div class="topclass-names">
                                SPEECH
                            </div>
                            {% elif option.data.value == "fx-o" %}
                        </div>
                        <div class="col-12 col-lg-4 offset-lg-1">
                            <div class="topclass-names">
                                SOUND EFFECTS
                            </div>
                            {% elif option.data.value == "ss-n" %}
                            <div class="topclass-names">
                                SOUNDSCAPES
                            </div>
                            {% endif %}
                            <div class="myradio mytooltip">
                                <span class="tooltiptext">{{ class_titles|dict_key:option.data.value }}</span>
                                {{ option }}
                            </div>
                            {% endfor %}
                        </div>     
                    </div>
                    
                    <div class="row">
                        <div class="col-12">
                            <div class="confidence-label">
                                {{form.confidence.label}}
                            </div>
                            <div class="error-confidence">
                                {{form.confidence.errors}}
                            </div>
                            <div class="horizontal-radio">
                                {% for choice in form.confidence %}
                                <div>{{choice}}</div>
                                {% endfor %}    
                            </div>
                        </div>
                    </div>

                    <div class="comment-label">
                        {{form.comment.label}}
                    </div>
                    <div class="error-class">
                        {{form.comment.errors}}
                    </div>
                    <div class="box-feedback">
                        {{form.comment}}
                    </div>

                    <div class="center" style="margin:30px 0px;">
                        {% if answered_sounds_size != all_sounds_size %}
                        <input type="submit" class="btn btn-dark" value="Continue with the next sound">
                        {% else %}
                        <input type="submit" class="btn btn-dark" value="Finish">
                        {% endif %}
                    </div>
                </div>
            </fieldset>
        </form>
        
    </div>
</div>
</div>

<script>
    document.getElementById('encoder_iframe').src="https://freesound.org/embed/sound/iframe/{{ test_sound.sound_id }}/simple/medium/"
    document.getElementById('encoder_iframe_small').src="https://freesound.org/embed/sound/iframe/{{ test_sound.sound_id }}/simple/small/"
</script>


{% endblock %}

classurvey/templates/classurvey/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Taxonomy Annotation Platform</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'classurvey/css/styles.css' %}">
    </head>
    
    <body>
        {% block content %}{% endblock content %}
        <footer class="footer-logo">
            Research by:
            <a target="_blank" href="https://www.upf.edu/web/mtg"><img src="{% static 'classurvey/images/UPF-MTG-logo.svg' %}" alt="UPF logo" class="logo"></a>
        </footer>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
        
    </body>
</html>

classurvey/templates/classurvey/batch_end.html
{% extends 'classurvey/base.html' %}

{% block content %}

<div class="pos-end">
    <div class="brd">
        <h3> 
            Thank you for your annotation!
        </h3>
        <p>
            Your answers have been submitted and recorded successfully and you can now safely close this page.
            If you want to <b>repeat and categorize a different set of sounds</b>, please click the button below.
        </p>

        <a href="{% url 'classurvey:home' %}" class="btn btn-dark btn-sm button-end">Annotate more</a>
    </div>
</div>

{% endblock content %}

classurvey/templates/classurvey/data_end.html
{% extends 'classurvey/base.html' %}

{% block content %}

<div class="pos-end">
    <div class="brd">
        <h3> 
            No more sounds to categorize!
        </h3>
        <p>
            There are no more sounds to categorize right now. Ask the principal researchers for more.
            <br>Thank you for your massive contribution :)
        </p>
    </div>
</div>

{% endblock content %}

classurvey/templates/classurvey/home.html
{% extends 'classurvey/base.html' %}

{% block content %}

{% if show_popup %}
<div class="popup">
    <p class="center">We detected that you have an ongoing annotation sound group left unfinished. Continuing with the previous one.</p>  
    <form method="POST">
        {% csrf_token %}
        <div>
            <button type="submit" name="action" value="continue" class="btn btn-outline-success btn-sm popup-button">Continue</button>
            <!-- <button type="submit" name="action" value="restart" class="btn btn-outline-danger btn-sm popup-button">Start a new one</button> -->
        </div>
    </form>
</div>
{% endif %}

<div class="container-start center">
    <h1>Welcome!</h1>
    <p>Click the button below to enter the<br><b>Broad Sound Taxonomy</b> annotation.</p>
    <a href="{% url 'classurvey:user_details' %}" class="btn btn-dark {% if show_popup %} disabled {% endif %}">Enter</a>
</div>

{% endblock content %}

classurvey/templates/classurvey/instructions.html
{% extends 'classurvey/base.html' %}

{% block content %}

<div class="container-main">
    <div class="card">
        <div class="card-header">
            <h1>Information for annotation process</h1>
        </div>
        <div class="card-body">
            <h4>Instructions:</h4>
            <ul>
                <li>Guidelines for annotation process:</li>
                <ol>
                    <li>Select the most appropriate category for each of the ~100 sounds that you'll be presented one by one.</li>
                    <li>During annotation choose a confidence level and write a comment, if necessary.</li>
                </ol>
                <li>The annotation takes approximately 20-40 minutes. We suggest completing it in a single sitting.</li>
                <li>It is preferable to be located in a <i>quiet</i> environment and use headphones so you can listen to the sounds without interferences.</li>
                <li>To ensure accurate results, please refrain from using the browser's <i>back button</i>.</li>
            </ul>

            <form action="{% url 'classurvey:user_details' %}" method="POST" style="display:block">
                {% csrf_token %}
                <br></br>
                        <!-- <label>
                            <input type="checkbox" name="consent" required>Problematic sound
                        </label> -->                
                <footer>
                    This research is carried out by Universitat Pompeu Fabra. You can contact us at <a href="mailto:panagiota.anastasopoulou@upf.edu">panagiota.anastasopoulou@upf.edu</a>
                    or <a href="mailto:frederic.font@upf.edu">frederic.font@upf.edu</a> for any technical problems or questions you might have.
                </footer>
                
                <div class="center" style="margin-top:30px;margin-bottom:10px">
                    <input type="submit" class="btn btn-dark" value="Go back">
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

classurvey/templates/classurvey/results.html
{% extends 'classurvey/base.html' %}

{% block content %}

<div style="max-width: 60%; margin: 0 auto;">
    <h3 class="center"> Results </h3>
    <p> Total annotated sounds: {{ annotations_cleaned }} (excluded {{ snd_sounds }} sounds not in Freesound) </p>
    <p> User count: {{ user_count }} </p>
    <p> Completed groups: {{ completed_groups }} ({{ uncompleted_groups }} groups not finished with number {{ uncompleted_group_names }}) </p>  
    <p> Remaining groups available: {{ remaining_groups }} </p>
    <p> Annotations by class:
        <ul>
            {% for class, count in class_counts.items %}
                <li>{{ class }}: {{ count }}</li>
            {% endfor %}
        </ul>
    </p>    
</div>

{% endblock content %}

classurvey/templates/classurvey/taxonomy.html
{% extends 'classurvey/base.html' %}
{% load dict_key %}

{% block content %}

<div class="container-main">
    <div class="card">
        <div class="card-header">
            <h1>Familiarization with the taxonomy</h1>
            <div class="center">
                Below is the taxonomy we have designed. Please, spend <b>4-5 minutes</b> looking at the top-level categories, the sub categories and their definition and examples to get familiar with them.
                Note that later during the categorization phase, you'll still be able to see all available taxonomy categories. Category definitions and examples will also be available by hovering over the categories' names.
            </div>  
        </div>

        <div class="card-body">
            <div class="container">
                <div class="d-none d-md-block titles">
                    <div class="row">
                        <div class="col-md-3 d-flex align-items-center">
                            Top-level category
                        </div>
                        <div class="col-md-9">
                            <div class="row">
                                <div class="col-md-4">
                                    Sub category
                                </div>
                                <div class="col-md-8">
                                    Definition and examples
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <hr style="border: 2px solid rgb(20, 10, 40);">

                {% for top_level, class_data in level_group.items %}
                <div class="row">
                    <div class="col-md-3 d-flex text-center align-items-center">
                        <div style="width: 100%"> 
                            <div><h3>{{ top_level }}</h3></div>
                            <div class="examples">{{ top_level_description|dict_key:top_level }}</div>
                        </div>
                    </div>
                    <div class="col-md-9"> 
                        {% for subclass in class_data %}
                        <div class="row">
                            <div class="col-md-4">
                                <span class="d-md-none">* </span><span>{{ subclass.class_name }} </span>
                            </div>
                            <div class="col-md-8">
                                <div>
                                    {{ subclass.description }}
                                </div>
                                <div class="examples">
                                    {% if subclass.examples != "" %}
                                        Examples: {{ subclass.examples }}
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                {% if not forloop.last %}
                    <hr>
                {% endif %}
                {% endfor %}
                <div class="center" style="margin-top: 20px;">
                    <a href="{% url 'classurvey:user_details' %}" class="btn btn-dark">Go back</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

classurvey/templates/classurvey/user_details.html
{% extends 'classurvey/base.html' %}

{% block content %}

<div class="container-main">
    <div class="card">
        <div class="card-header">
            <h1>Annotator data</h1>
        </div>
        <div class="card-body">
            <form method="post" novalidate>
                {% csrf_token %}
                <div class="details center">
                        
                    <div class="error-username">
                        {{ form.user_name.errors }}
                    </div>
                    <div>
                        {{ form.user_name.label }}
                    </div>
                    <div>
                        {{ form.user_name }}
                    </div>
                    
                    <br>
                    Look <a href="{% url 'classurvey:instructions' %}">the instructions</a>
                    <br><br>
                    Revise <a href="{% url 'classurvey:taxonomy' %}"> taxonomy</a>
                    <br><br><br>

                    <div class="center">
                        <input type="submit" class="btn btn-dark" value="Start annotating sounds">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content %}